IKASAN-1734 - first pass of creating a cli distribution zip and using…
ikasanEIP/ikasan pull request #890
Opened 2021-01-09 13:03 UTC by kieronedwards

… in filesystem archetype to review. Notes

- Created a ikasan-simple version of the scripts that dont use the config service
- The batch scripts dont run on my windows machine - have these been tested
- In ikasan.sh assume defaults for config-service, but no clean way to derive the module name (using the directory name is not clean). This could be put in env.sh - but why not use local application.properties ?
- Suggest we should re-consider having a common application.properties in addition to using the config-service (which only has environment specific properties). The module name would be in these properties
- Even if config-service properties not passed in the shell still tries to locate a config-service
- shell unit tests are failing despite no change to codebase :- (- File [.\pid\Module_sampleProcess] not found)
- corrected naming of some poms

2021-01-09 21:34 UTC, andrzej-majewski commented on ikasaneip/cli/bin/ikasan.sh
> +CONFIG_SERVICE_URL=${CONFIG_SERVICE_URL:-'http://localhost:8880'}
is this bash notation to defaulting variable

2021-01-10 19:30 UTC, mitcje commented on ikasaneip/cli/bin/ikasan.sh
> +CONFIG_SERVICE_URL=${CONFIG_SERVICE_URL:-'http://localhost:8880'}
I would keep the script very simple so its more likely to work across shells

2021-01-11 23:10 UTC, andrzej-majewski approved these changes

2021-01-11 23:17 UTC, andrzej-majewski approved these changes, later dismissed

2021-01-12 21:31 UTC, mitcje requested changes

2021-01-12 21:31 UTC, mitcje commented on ikasaneip/cli/shell/bin/ikasan-simple.bat
>  set currentDir=%CD%
Should we not be loading a simple env.bat ?

2021-01-12 21:31 UTC, mitcje commented on ikasaneip/cli/shell/bin/ikasan-simple.sh
> +# this script assumes you are using the filesystem for application.properties
Should we not be loading a simple env.sh ?

2021-01-12 21:31 UTC, mitcje commented on ikasaneip/developer/mvn-archetype/ikasan-standalone-filesystem-im/src/main/resources/archetype-resources/bin/env.sh
> -#!/bin/bash
Why are we deleting this?

2021-01-12 21:31 UTC, mitcje commented on ikasaneip/developer/mvn-archetype/ikasan-standalone-filesystem-im/src/main/resources/archetype-resources/bin/env.bat
> -echo "No additional environment settings."
Why are we deleting this?

2021-01-14 20:52 UTC, mitcje approved these changes

2021-01-14 20:52 UTC, merged