IKASAN-1894 - Add ComponentFactory spec interface, ComponentFactory b…
ikasanEIP/ikasan pull request #971
Opened 2021-08-22 23:49 UTC by kieronedwards

…ase classes, and Jms Component Factory classes

2021-08-24 22:05 UTC, mitcje requested changes
@kieronedwards  please can you clarify the comments below - should we not be isolating spring specific JMS facets as we do have a native JMS client as well.

2021-08-24 22:05 UTC, mitcje commented on ikasaneip/component-factory/spring/jms/src/main/java/org/ikasan/component/factory/jms/JmsComponentFactory.java
> +package org.ikasan.component.factory.jms;
Should this not live in an AMQ specific package as it has AMQ specifics - its not just using JMS spec.

2021-08-24 22:05 UTC, mitcje commented on ikasaneip/component-factory/spring/jms/src/main/java/org/ikasan/component/factory/jms/consumer/JmsConsumerComponentFactory.java
> +    public JmsContainerConsumer create(String nameSuffix, String configPrefix) {
This is spring specific - should this not live in a different package ? Where would we put the native JMS client for instance ?

2021-08-24 22:05 UTC, mitcje commented on ikasaneip/component-factory/spring/jms/src/main/java/org/ikasan/component/factory/jms/producer/JmsProducerComponentFactory.java
> +    public JmsTemplateProducer create(String nameSuffix, String configPrefix) {
Again spring specific - where would we implement the native JMS publisher version?

2021-08-25 16:56 UTC, kieronedwards commented on ikasaneip/component-factory/spring/jms/src/main/java/org/ikasan/component/factory/jms/JmsComponentFactory.java
> +package org.ikasan.component.factory.jms;
@mitcje  This is has proven to work with both AMQ and JBOSS Messaging we can extend to others as needed.

2021-08-25 16:59 UTC, kieronedwards commented on ikasaneip/component-factory/spring/jms/src/main/java/org/ikasan/component/factory/jms/consumer/JmsConsumerComponentFactory.java
> +    public JmsContainerConsumer create(String nameSuffix, String configPrefix) {
correct - all component factory implementations live under the spring maven module.

2021-08-25 16:59 UTC, kieronedwards commented on ikasaneip/component-factory/spring/jms/src/main/java/org/ikasan/component/factory/jms/producer/JmsProducerComponentFactory.java
> +    public JmsTemplateProducer create(String nameSuffix, String configPrefix) {
@mitcje see above comment

2021-08-26 18:55 UTC, mitcje approved these changes

2021-08-26 20:00 UTC, merged